### ISSUE TITLE
 Which versions are supported

### ISSUE THREAD

**Issue by XueMeijing** [codespaces-contrib/codeswing#19]
when i install codeswing, an error appeared 
![image](https://user-images.githubusercontent.com/35559153/103496727-3a898600-4e7a-11eb-96df-85e1ed6f303a.png)

**Comment by XueMeijing** [comment]
it doesn't support VSCode 1.50.1

**Comment by lostintangent** [comment]
It currently requires 1.51, which is why you're seeing that message. Is it possible for you to upgrade VS Code? Otherwise, I'd need to audit the APIs I'm using and see if I can downgrade the requirement to 1.50.

**Comment by XueMeijing** [comment]
> s it possible for y

okok,i'll upgrade it latter and have a try , thank u very much

**Comment by XueMeijing** [comment]
> It currently requires 1.51, which is why you're seeing that message. Is it possible for you to upgrade VS Code? Otherwise, I'd need to audit the APIs I'm using and see if I can downgrade the requirement to 1.50.

it works well on 1.52.1, very nice extension

**Comment by lostintangent** [comment]
That's great to hear! I'll go ahead and close this as resolved, since you seem to be unblocked 👍 That said, please don't hesitate to let me know if you have any feedback. Additionally, if you end up finding CodeSwing useful, a [review in the marketplace](https://marketplace.visualstudio.com/items?itemName=codespaces-Contrib.codeswing&ssr=false#review-details) would be greatly appreciated. Thanks!
